### PR TITLE
documentation: Add how_to_model_a_study.md

### PR DESCRIPTION
**Pull request by kmarinushkin**
Quick start guide to modelling in `witness-core`

Signed-off-by: Kirill Marinushkin <k.marinushkin@gmail.com>

### CODE REVIEW

**Comment by MichaelTiemannOSC** [comment]
Kirill, thank you for taking this initiative!

I have one question, which is about .puml files.  Elsewhere in the project I have introduced mermaid: https://github.com/os-climate/ITR/blob/main/docs/Calculation.md. I'm not saying that mermaid is better than puml, but if we are going to create diagrams, I suggest we try to do so with a common approach.  If .puml is better than mermaid for this and other use cases, I'll be happy to change my docs to use better a better diagraming language/approach.

**Comment by kmarinushkin** [comment]
Thanks, @MichaelTiemannOSC  :)

this initiative is actually proposed by @sostrades-matthieu-meaux, as a first step for me, to join `witness-core` development.

>  suggest we try to do so with a common approach

i fully agree, I am always in favour of common style in projects. I just didn't know, that some common style for diagrams already exists. Sure, I will switch my diagrams to `mermaid`.

> If .puml is better than mermaid for this and other use cases

I have an impression, that `mermaid` will do the job, but I need to try it first.
.puml stands for `PlantUML`, a tool for UML diagrams, if you are interested to have a look.
What makes `mermaid` interesting for me - is that GitHub seems to support it natively. My diagrams I needed to convert to .svg images, to insert them into documentation.

Even if capabilities of `mermaid` are not as rich as of `PlantUML` - it could be enough, for our purpose. I will give it a try.

**Comment by kmarinushkin** [comment]
Thanks for the proposal, @MichaelTiemannOSC!

I pushed mermaid diagrams - they look clear to understand, for the documentation purpose, and simplify the way it's stored in the repo!

**Review by sostrades-tchevalier — APPROVED** [review]

**Comment by kmarinushkin** [comment]
Hello @sostrades-tchevalier, 

Since you approved the PR, may I ask you to merge it?
I don't have such permissions in this repo, and I have no feedback from Matthieu.

I don't like long hanging PRs, and would prefer to merge it or cancel it sooner then later

**Comment by sostrades-tchevalier** [comment]
Hi Kirill,

Thanks for the head up and sorry for the delay, we’re still half way from our legacy internal DevOps  to the public one !

We will process that quickly 😊

Best regards,

Thierry

**Pull request merged**
